### PR TITLE
New web

### PR DESCRIPTION
**Pull request by sarkaaa**
I coded new design for Spacewalk web. The text content is the same as it was in past. The web is fully responsive. Visit the live [demo](http://www.sarkachwastkova.cz/spacewalk) . Feel free to comment on this PR and let me know if there are some bugs or something else that need to be changed.

**Links for used technologies:**
- Bootstrap (license MIT) - https://getbootstrap.com/
- Lightbox2 (license MIT) - http://lokeshdhakar.com/projects/lightbox2/
- glyphicons/font awesome (license MIT) - http://fontawesome.io/
- ScrollReveal (license MIT) - http://scrollrevealjs.org

### CODE REVIEW

**Comment by Pajinek** [comment]
Wow :) Super +1

**Comment by Pajinek** [comment]
Some notes. Mostly about homepage and it is only tip ;) 
* homepage is rather empty. I think that a user should see some important link and facts.
    * button for download and information about latest release (look at site https://www.theforeman.org/)
    * some basic text about spacewalk 
* more graphic - icons. The pages are little bit sad. (https://kubernetes.io/). For example icon for IRC, github..  etc.

And thank you. Good work!!

**Comment by sarkaaa** [comment]
Hello.
Thank you for response. I agree with you, I didn't change the text content, I changed only the webdesign. If you have some info for community to add, let me know and send me content to add. I will create another PR. 
I would like to add some graphics elements, but there is problem with the idea. I don't know a lot about the Spacewalk, so if you have some idea about specific graphics images or illustrations, you can send me photo of some sketch in the paper, I will draw it in computer and I will add it to the webpage as a PR.

In case of merge this PR, I recommend to merge it without your proposed changes.

**Comment by BlackSmith** [comment]
Hi, it is really nice. I have only few notes:

- on regular page, there can be slimmer header. The height 55px can be fine and logo on left top corner.
- maybe little more contrast color of web links.

good job :)

**Comment by jiridostal** [comment]
As it's very popular within the team, I'm merging this pull request as it is. Any further changes may be applied by other PR. As for comments above, could you please create separate issues so that we could track and discuss it on a single place?
Thank you

**Comment by sarkaaa** [comment]
Hi, thank you a lot :). I'm glad for your tips about the webdesign and your responses.
@BlackSmith I will take a look at this and fix it by the time. Thank you for your comment.
@jiridostal Thank you for merging this. I will create separate issues for each problem/recommendation mention above.

**Pull request merged**
